CREATE DATABASE IF NOT EXISTS crud_aula
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

USE crud_aula;

CREATE TABLE IF NOT EXISTS usuarios (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);