CREATE DATABASE IF NOT EXISTS aula_erros
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

USE aula_erros;

CREATE TABLE IF NOT EXISTS usuarios (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);